language: ruby

rvm:
  - 2.4.0
  - 2.3.4
  - rbx-3.75
  - jruby-19mode # JRuby in 1.9 mode

matrix:
  allow_failures:
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: rbx-3.75
    - rvm: 2.2.2

services:
  - couchdb

# temporarily disable the script
script: bundle exec rake test_ragios
