version: '3'
services:
  couchdb:
    image: "klaemo/couchdb"
    expose:
      - "5984"
    ports:
      - 5984:5984

  ragios:
    build: .
    links:
      - couchdb:couchdb
    depends_on:
      - couchdb
