version: '3'
services:
  couchdb:
    image: "apache/couchdb:1.7.1"
    expose:
      - "5984"
    ports:
      - 5984:5984

  database_setup:
    image: "obiora/ragios:latest"
    links:
      - couchdb:couchdb
    environment:
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    tty: true
    stdin_open: true
    entrypoint: bundle exec ruby bin/database_setup.rb

  web:
    image: "obiora/ragios:latest"
    depends_on:
      - database_setup
    links:
      - couchdb:couchdb
      - recurring_jobs:recurring_jobs
      - events:events
    environment:
      RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS: recurring_jobs
      RAGIOS_EVENTS_RECEIVER_ADDRESS: events
      RAGIOS_WEB_SERVER_ADDRESS: 'tcp://0.0.0.0:5041'
      RAGIOS_WEB_SERVER_ENV: production
      RAGIOS_ENV: production
      RAGIOS_LOG_LEVEL: info
      SES_AWS_ACCESS_KEY_ID:
      SES_AWS_SECRET_ACCESS_KEY:
      AWS_SES_SEND_FROM:
      AWS_SES_ENDPOINT:
      RAGIOS_ADMIN_USERNAME:
      RAGIOS_ADMIN_PASSWORD:
      RAGIOS_AUTHENTICATION:
      RAGIOS_AUTH_TIMEOUT:
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    expose:
      - "5041"
    ports:
      - "5041:5041"
    tty: true
    stdin_open: true
    entrypoint: bundle exec pumactl -F server.rb start

  recurring_jobs:
    image: "obiora/ragios:latest"
    depends_on:
      - database_setup
    links:
      - couchdb:couchdb
      - events:events
    environment:
      RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS: '0.0.0.0'
      RAGIOS_EVENTS_RECEIVER_ADDRESS: events
      RAGIOS_WORKERS_PUSHER_ADDRESS: '0.0.0.0'
      RAGIOS_ENV: production
      RAGIOS_LOG_LEVEL: info
      SES_AWS_ACCESS_KEY_ID:
      SES_AWS_SECRET_ACCESS_KEY:
      AWS_SES_SEND_FROM:
      AWS_SES_ENDPOINT:
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    expose:
      - "5042"
      - "5043"
    tty: true
    stdin_open: true
    entrypoint: bundle exec ruby bin/recurring_jobs_ctl.rb run

  workers:
    image: "obiora/ragios:latest"
    depends_on:
      - database_setup
    links:
      - couchdb:couchdb
      - events:events
      - recurring_jobs:recurring_jobs
      - notifications:notifications
    environment:
      RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS: recurring_jobs
      RAGIOS_EVENTS_RECEIVER_ADDRESS: events
      RAGIOS_WORKERS_PUSHER_ADDRESS: recurring_jobs
      RAGIOS_NOTIFICATIONS_RECEIVER_ADDRESS: notifications
      RAGIOS_ENV: production
      RAGIOS_LOG_LEVEL: info
      SES_AWS_ACCESS_KEY_ID:
      SES_AWS_SECRET_ACCESS_KEY:
      AWS_SES_SEND_FROM:
      AWS_SES_ENDPOINT:
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    tty: true
    stdin_open: true
    entrypoint: bundle exec ruby bin/workers_ctl.rb run

  events:
    image: "obiora/ragios:latest"
    depends_on:
      - database_setup
    links:
      - couchdb:couchdb
    environment:
      RAGIOS_EVENTS_RECEIVER_ADDRESS: '0.0.0.0'
      RAGIOS_ENV: production
      RAGIOS_LOG_LEVEL: info
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    expose:
      - "5045"
    tty: true
    stdin_open: true
    entrypoint: bundle exec ruby bin/events_ctl.rb run

  notifications:
    image: "obiora/ragios:latest"
    depends_on:
      - database_setup
    links:
      - couchdb:couchdb
      - events:events
    environment:
      RAGIOS_NOTIFICATIONS_RECEIVER_ADDRESS: '0.0.0.0'
      RAGIOS_EVENTS_RECEIVER_ADDRESS: events
      RAGIOS_ENV: production
      RAGIOS_LOG_LEVEL: info
      SES_AWS_ACCESS_KEY_ID:
      SES_AWS_SECRET_ACCESS_KEY:
      AWS_SES_SEND_FROM:
      AWS_SES_ENDPOINT:
      COUCHDB_ADMIN_USERNAME:
      COUCHDB_ADMIN_PASSWORD:
    expose:
      - "5044"
    tty: true
    stdin_open: true
    entrypoint: bundle exec ruby bin/notifications_ctl.rb run
