version: '3'
services:
  couchdb:
    image: "klaemo/couchdb"
    expose:
      - "5984"
    ports:
      - 5984:5984

  unit_tests:
    build: .
    links:
      - couchdb:couchdb
    volumes:
      - .:/usr/src/ragios
    environment:
      RAGIOS_COUCHDB_ADDRESS: couchdb
