#!/usr/bin/env ruby
require "thor"

class RagiosCLI < Thor

  desc "console", "Open Ragios Interactive Shell"
  def console
  	ragios_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'ragios'))
    config = ragios_dir + '/config'
    irb = "bundle exec pry -r #{config}"
    exec(irb)
  end

  desc "server start | restart | stop", "Run Ragios Server"
  def server(option=nil)
    exec('bundle exec pumactl -F server.rb start') if option == 'start'
    if option == 'restart'
      puts "Restarting Ragios..."
      exec('bundle exec pumactl -F server.rb restart')
    end
    if option == 'stop'
      puts "Stopping Ragios..."
      exec('bundle exec pumactl -F server.rb stop')
    end
    if option == 'phased-restart'
      puts "Ragios phased-restart in progress..."
      exec('bundle exec pumactl -F server.rb phased-restart -p tmp/pids/puma.pid')
    end

    puts "Usage: ragios server start | stop | restart | phased-restart"
  end

end

RagiosCLI.start(ARGV)
