#!/usr/bin/ruby
 
  require 'rubygems'
  require "bundler/setup"        
  require 'daemons'

  require 'lib/ragios'

  options = {
  :app_name   => "ragios",
  :dir_mode   => :script,
  :dir        => 'log', 
  :log_output => true,
  :monitor    => true
  }

Daemons.run('main.rb', options)


