apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workers
    spec:
      containers:
      - command:
        - bundle
        - exec
        - ruby
        - bin/workers_ctl.rb
        - run
        env:
        - name: RAGIOS_ENV
          value: production
        - name: RAGIOS_EVENTS_RECEIVER_ADDRESS
          value: events
        - name: RAGIOS_LOG_LEVEL
          value: info
        - name: RAGIOS_NOTIFICATIONS_RECEIVER_ADDRESS
          value: notifications
        - name: RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS
          value: recurring-jobs
        - name: RAGIOS_WORKERS_PUSHER_ADDRESS
          value: recurring-jobs
        image: obiora/ragios:v0.7.1.2
        name: workers
        ports:
        - containerPort: 5043
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
